<?php

namespace App\Exports;

use App\Models\Indent;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Events\BeforeSheet;

class IndentExport implements FromCollection, WithHeadings, WithMapping, WithCustomStartCell, WithEvents
{
    protected $indent;

    public function __construct(Indent $indent)
    {
        $this->indent = $indent->load('items.product', 'user');
    }

    public function collection()
    {
        return $this->indent->items;
    }

    public function startCell(): string
    {
        return 'A6';
    }

    public function headings(): array
    {
        return [
            'Product Name',
            'Item Code',
            'Pack Name',
            'Demand Qty',
            'Unit',
            'Stock (Box)',
            'Stock (KG/LTR)',
            'Final Indent (Box)',
            'Completed Qty (Box)'
        ];
    }

    public function map($item): array
    {
        return [
            $item->product_name ?: ($item->product->name ?? 'N/A'),
            $item->product->item_code ?? 'N/A',
            $item->product->pack_name ?? 'N/A',
            $item->demand_qty,
            $item->demand_unit,
            $item->stock_box,
            $item->stock_kg,
            $item->final_qty_box,
            (int)$item->completed_qty
        ];
    }

    public function registerEvents(): array
    {
        return [
            BeforeSheet::class => function(BeforeSheet $event) {
                $sheet = $event->sheet->getDelegate();
                
                // Styling and Header Info
                $sheet->mergeCells('A1:I1');
                $sheet->setCellValue('A1', 'MATERIAL INDENT REPORT');
                $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(16);
                $sheet->getStyle('A1')->getAlignment()->setHorizontal('center');

                $sheet->setCellValue('A2', 'STORE / BRANCH:');
                $sheet->setCellValue('B2', "{$this->indent->branch_name} ({$this->indent->branch_code})");
                
                $sheet->setCellValue('A3', 'GENERATED BY:');
                $sheet->setCellValue('B3', $this->indent->user->name ?? 'System');

                $sheet->setCellValue('A4', 'INDENT DATE:');
                $sheet->setCellValue('B4', date('d-M-Y', strtotime($this->indent->indent_date)));

                $sheet->getStyle('A2:A4')->getFont()->setBold(true);
            },
        ];
    }
}
