<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Events\BeforeSheet;
use Maatwebsite\Excel\Concerns\Exportable;

class MRPExport implements FromCollection, WithHeadings, WithMapping, WithCustomStartCell, WithEvents
{
    use Exportable;

    protected $results;
    protected $summary;
    protected $branch;

    public function __construct(array $results, array $summary, $branchCode = null)
    {
        $this->results = collect($results);
        $this->summary = $summary;
        $this->branch = \App\Models\Branch::where('code', $branchCode)->first();
    }

    public function collection()
    {
        return $this->results;
    }

    public function startCell(): string
    {
        return 'A8';
    }

    public function headings(): array
    {
        return [
            'Raw Material',
            'Item Code',
            'Required Qty',
            'UOM',
            'Current Stock',
            'Shortfall'
        ];
    }

    public function map($item): array
    {
        return [
            $item['name'],
            $item['item_code'],
            number_format($item['required_qty'], 3, '.', ''),
            $item['uom'],
            number_format($item['current_stock'], 3, '.', ''),
            number_format($item['shortfall'], 3, '.', '')
        ];
    }

    public function registerEvents(): array
    {
        return [
            BeforeSheet::class => function(BeforeSheet $event) {
                $sheet = $event->sheet->getDelegate();
                
                // Styling and Header Info
                $sheet->mergeCells('A1:F1');
                $sheet->setCellValue('A1', 'MATERIAL REQUIREMENT PLANNING (MRP) REPORT');
                $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(16);
                $sheet->getStyle('A1')->getAlignment()->setHorizontal('center');

                $sheet->setCellValue('A2', 'SOURCE BRANCH:');
                $sheet->setCellValue('B2', $this->branch ? "{$this->branch->name} ({$this->branch->code})" : "CONSOLIDATED (ALL BRANCHES)");
                
                $sheet->setCellValue('A3', 'GENERATED BY:');
                $sheet->setCellValue('B3', auth()->user()->name ?? 'System');

                $sheet->setCellValue('A4', 'REPORT DATE:');
                $sheet->setCellValue('B4', date('d-M-Y H:i'));

                // Production Summary
                $sheet->setCellValue('A6', 'PLANNING SUMMARY:');
                $sheet->getStyle('A6')->getFont()->setBold(true);
                
                $summaryText = "";
                foreach($this->summary as $s) {
                    $summaryText .= "{$s['name']} ({$s['pack_name']}): {$s['quantity']} Box | ";
                }
                $sheet->setCellValue('B6', rtrim($summaryText, " | "));

                $sheet->getStyle('A2:A4')->getFont()->setBold(true);
            },
        ];
    }
}
