<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Material Indent - {{ $indent->branch_name }}</title>
    <style>
        @page { margin: 30px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; color: #333; font-size: 11px; margin: 0; }
        .header { border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 30px; }
        .title { font-size: 22px; font-weight: bold; text-transform: uppercase; color: #000; }
        .meta-grid { width: 100%; margin-top: 15px; }
        .meta-grid td { vertical-align: top; }
        .label { font-weight: normal; color: #666; font-size: 10px; text-transform: uppercase; }
        .value { font-weight: bold; color: #000; font-size: 13px; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 25px; }
        th { background: #f4f4f4; text-align: left; padding: 12px 8px; border: 1px solid #ddd; font-size: 10px; text-transform: uppercase; }
        td { padding: 10px 8px; border: 1px solid #ddd; font-size: 12px; }
        
        .product-name { font-weight: bold; }
        .product-pack { color: #888; font-size: 9px; margin-top: 2px; }
        
        .qty-col { text-align: center; }
        .final-qty { text-align: right; font-weight: bold; font-size: 14px; color: #4f46e5; }
        
        .total-row { background: #eee; font-weight: bold; }
        .total-label { text-align: right; padding-right: 15px; text-transform: uppercase; font-size: 11px; }
        .total-val { text-align: right; font-size: 18px; color: #000; }
        
        .footer { margin-top: 50px; font-style: italic; font-size: 9px; text-align: center; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Material Indent</div>
        <table class="meta-grid">
            <tr>
                <td width="50%">
                    <div class="label">Target Store / Branch</div>
                    <div class="value">{{ $indent->branch_name }} ({{ $indent->branch_code }})</div>
                </td>
                <td width="50%" style="text-align: right;">
                    <div class="label">Indent Date / ID</div>
                    <div class="value">{{ date('d M, Y', strtotime($indent->indent_date)) }} | #{{ str_pad($indent->id, 5, '0', STR_PAD_LEFT) }}</div>
                    <div class="label" style="margin-top:5px;">Generated By</div>
                    <div class="value" style="font-size: 11px;">{{ $indent->user->name ?? 'System' }}</div>
                </td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                <th width="40%">Product Name</th>
                <th width="12%">Pack</th>
                <th width="14%" style="text-align: center;">Target Stock</th>
                <th width="17%" style="text-align: right;">Asked (Box)</th>
                <th width="17%" style="text-align: right;">Completed</th>
            </tr>
        </thead>
        <tbody>
            @foreach($indent->items as $item)
            <tr>
                <td>
                    <div class="product-name">{{ $item->product_name }}</div>
                </td>
                <td>{{ $item->product->pack_name ?? 'N/A' }}</td>
                <td class="qty-col">{{ number_format($item->stock_box, 2) }}</td>
                <td class="final-qty" style="color: #666; font-size: 12px;">{{ number_format($item->final_qty_box, 0) }}</td>
                <td class="final-qty">{{ number_format($item->completed_qty, 0) }}</td>
            </tr>
            @endforeach
            <tr class="total-row">
                <td colspan="4" class="total-label">Total Indent volume (Boxes)</td>
                <td class="total-val">{{ number_format($indent->items->sum('completed_qty'), 0) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        This is a computer generated document. Generated on {{ date('d-m-Y H:i:s') }}
    </div>
</body>
</html>
