<!DOCTYPE html>
<html>
<head>
    <title>MRP Planning Report</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        .header h1 { color: #4f46e5; margin: 0; font-size: 24px; }
        .header p { margin: 5px 0; color: #666; }
        .section-title { background: #f8fafc; padding: 8px 12px; font-weight: bold; border-left: 4px solid #4f46e5; margin: 20px 0 10px 0; uppercase; font-size: 10px; letter-spacing: 1px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #f1f5f9; color: #475569; font-weight: bold; text-align: left; padding: 10px; border: 1px solid #e2e8f0; font-size: 10px; text-transform: uppercase; }
        td { padding: 10px; border: 1px solid #e2e8f0; vertical-align: top; }
        .text-right { text-align: right; }
        .font-bold { font-weight: bold; }
        .text-danger { color: #e11d48; }
        .text-success { color: #059669; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>InvoFlow Production Planning</h1>
        <p>MRP Calculation Report - {{ date('d M, Y H:i') }}</p>
        <p>Branch: {{ $branch ?? 'All Permitted Branches' }}</p>
    </div>

    <div class="section-title">Production Summary (Target)</div>
    <table>
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Item Code</th>
                <th>Pack Size</th>
                <th class="text-right">Planned Qty</th>
            </tr>
        </thead>
        <tbody>
            @foreach($summary as $item)
            <tr>
                <td class="font-bold">{{ $item['name'] }}</td>
                <td>{{ $item['item_code'] ?? 'N/A' }}</td>
                <td>{{ $item['pack_name'] ?? 'N/A' }}</td>
                <td class="text-right font-bold">{{ number_format($item['quantity'], 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Material Requirements (Exploded)</div>
    <table>
        <thead>
            <tr>
                <th>Raw Material</th>
                <th>Item Code</th>
                <th class="text-right">Required</th>
                <th class="text-right">In Stock</th>
                <th class="text-right">Shortfall</th>
            </tr>
        </thead>
        <tbody>
            @foreach($results as $res)
            <tr>
                <td>{{ $res['name'] }} <br><small style="color:#64748b">{{ $res['uom'] ?? '' }}</small></td>
                <td>{{ $res['item_code'] }}</td>
                <td class="text-right font-bold">{{ number_format($res['required_qty'], 2) }}</td>
                <td class="text-right">{{ number_format($res['current_stock'], 2) }}</td>
                <td class="text-right font-bold {{ $res['shortfall'] > 0 ? 'text-danger' : 'text-success' }}">
                    {{ $res['shortfall'] > 0 ? number_format($res['shortfall'], 2) : 'OK' }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by InvoFlow System &bull; Confidential &bull; Page 1
    </div>
</body>
</html>
