<!DOCTYPE html>
<html>
<head>
    <title>Mobile Stock Report</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 10px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 18px; color: #1e293b; }
        .header p { margin: 5px 0; color: #64748b; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #f1f5f9; color: #475569; font-weight: bold; text-align: left; padding: 8px; border-bottom: 2px solid #e2e8f0; }
        td { padding: 8px; border-bottom: 1px solid #f1f5f9; }
        .text-right { text-align: right; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 8px; color: #94a3b8; padding: 10px 0; }
        .badge { background: #e2e8f0; padding: 2px 6px; border-radius: 4px; font-size: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Inventory Flow</h1>
        <p>MOBILE LIVE STOCK REPORT - {{ now()->format('d M, Y h:i A') }}</p>
        <div style="font-size: 9px; margin-top: 10px;">
            <span>Branch: <strong>{{ $selectedBranch ?: 'ALL BRANCHES' }}</strong></span>
            <span style="margin-left: 20px;">Unit: <strong>{{ strtoupper($displayUnit) }}</strong></span>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="40%">Item Name</th>
                <th width="15%">Code</th>
                <th width="15%">Pack</th>
                <th width="15%" class="text-right">Stock</th>
                <th width="15%">Unit</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData as $data)
            <tr>
                <td>{{ $data['product']->name }}</td>
                <td><span class="badge">{{ $data['product']->item_code }}</span></td>
                <td>{{ $data['product']->pack_name }}</td>
                <td class="text-right"><strong>{{ number_format($data['stock'], 2) }}</strong></td>
                <td>{{ $data['unit'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by InventoryFlow PWA • Page {PAGENO}
    </div>
</body>
</html>
