<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Indent Print - {{ $indent->branch_name }}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; margin: 40px; }
        .header { display: flex; justify-content: space-between; border-bottom: 3px solid #333; padding-bottom: 10px; margin-bottom: 30px; }
        .title { font-size: 24px; font-weight: bold; text-transform: uppercase; }
        .meta { text-align: right; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f4f4f4; text-align: left; padding: 12px; border: 1px solid #ddd; font-size: 12px; text-transform: uppercase; }
        td { padding: 10px; border: 1px solid #ddd; font-size: 13px; }
        .footer { margin-top: 40px; font-style: italic; font-size: 11px; text-align: center; color: #777; }
        .total-row { font-weight: bold; background: #eee; }
        @media print {
            .no-print { display: none; }
            body { margin: 0; }
        }
    </style>
</head>
<body onload="window.print()">
    <div class="header">
        <div>
            <div class="title">Material Indent</div>
            <div style="font-size: 14px; color: #666;">Target: <strong>{{ $indent->branch_name }} ({{ $indent->branch_code }})</strong></div>
        </div>
        <div class="meta">
            <div>Date: <strong>{{ date('d M, Y', strtotime($indent->indent_date)) }}</strong></div>
            <div>Generated by: {{ $indent->user->name ?? 'System' }}</div>
            <div>ID: #{{ str_pad($indent->id, 5, '0', STR_PAD_LEFT) }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Pack</th>
                <th style="text-align: center;">Live Stock (Box)</th>
                <th style="text-align: center;">Required Qty</th>
                <th style="text-align: right;">Final Boxes</th>
            </tr>
        </thead>
        <tbody>
            @foreach($indent->items as $item)
            <tr>
                <td>{{ $item->product_name ?: ($item->product->name ?? 'N/A') }}</td>
                <td>{{ $item->product->pack_name ?? 'N/A' }}</td>
                <td style="text-align: center;">{{ number_format($item->stock_box, 2) }}</td>
                <td style="text-align: center;">{{ $item->demand_qty }} {{ strtoupper($item->demand_unit) }}</td>
                <td style="text-align: right;"><strong>{{ number_format($item->final_qty_box, 0) }}</strong></td>
            </tr>
            @endforeach
            <tr class="total-row">
                <td colspan="4" style="text-align: right;">TOTAL INDENT VOLUME (BOXES)</td>
                <td style="text-align: right; font-size: 16px;">{{ number_format($indent->total_boxes, 0) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        This is a computer generated document. Printed on {{ date('d-m-Y H:i:s') }}
        <div class="no-print" style="margin-top: 20px;">
            <button onclick="window.close()" style="padding: 10px 20px; cursor: pointer;">Close Window</button>
        </div>
    </div>
</body>
</html>
